### ISSUE TITLE
SSHLauncher: module load before it does python3 -m IPython profile create

### ISSUE THREAD

**Issue by sigurdurb** [minrk/ipyparallel-ssh-mpi-demo#1]
Using the method described in the README I am not able to do  run `python3 -m IPython profile create --profile-dir .ipython/profile_remote
because I have to load python at least first, but also mpi:

```
module load python/3.6.1
module load gnu
module load openmpi/gnu
```

.. somewhere before in the same session. Is there a method in IPyparallel I can use?
I've been trying to find one without luck.

Jupyterhub log from trying to start a cluster from the IPython cluster notebook tab with 1 engine:
```
[E 2023-05-14 14:19:38.836 SingleUserNotebookApp web:1789] Uncaught exception POST /user/sigurdur14/ipyparallel/clusters/jotunn%3A (10.3.27.16)
    HTTPServerRequest(protocol='http', host='local', method='POST', uri='/user/sigurdur14/ipyparallel/clusters/remote%3A', version='HTTP/1.1', remote_ip='10.3.27.16')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.8/site-packages/ipyparallel/nbextension/handlers.py", line 137, in post
        await cluster.start_cluster(n=n)
      File "/opt/conda/lib/python3.8/site-packages/ipyparallel/cluster/cluster.py", line 776, in start_cluster
        await self.start_controller()
      File "/opt/conda/lib/python3.8/site-packages/ipyparallel/cluster/cluster.py", line 654, in start_controller
        r = self.controller.start()
      File "/opt/conda/lib/python3.8/site-packages/ipyparallel/cluster/launcher.py", line 1278, in start
        check_output(
      File "/opt/conda/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ssh', 'remote', 'python3 -m IPython profile create --profile-dir .ipython/profile_remote']' returned non-zero exit status 127.
[W 2023-05-14 14:19:38.842 SingleUserNotebookApp handlers:617] Unhandled error
```

**Comment by minrk** [comment]
This could be better supported, but I think the best way will be to set `c.SSHLauncher.remote_python` to a _script_ that prepares the environment and then does `exec python3 "$@"`.

So write your script:

```bash
#!/bin/bash -l
# this file is in /opt/whatever/launch-python-for-ipyparallel-ssh

module load python/3.6.1
module load gnu
module load openmpi/gnu

exec python "$@"
```

(I put `bash -l` because it creates a login shell, so rc files, profiles, etc. will be sourced. That may not be necessary for you, but tends to result in the most "expected" environment for most folks.)

and then in your ipcluster_config.py:

```python
c.SSHLauncher.remote_python = "/opt/whatever/launch-python-for-ipyparallel-ssh"
```

**Comment by sigurdurb** [comment]
Thanks, I was able to use these configurations in a project I did connecting Jupyterhub to a live MPI server.
I've made it public here with more technical documentation in a README and a more high level documentation and report in a pdf: #[sigurdurb/jupyterhub-ipyparallel](https://github.com/sigurdurb/jupyterhub-ipyparallel)
